name: weather_service
description: Weather Api Service Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.5.4
  build_runner: ^2.1.10
  freezed: ^2.2.0
